# Generated by Django 5.1.4 on 2026-06-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ja', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField()),
                ('time_range', models.CharField(blank=True, max_length=50)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', '出席'), ('absent', '欠席'), ('event', '行事')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.child')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
